spring.application.name=movie-booking-app
#spring.datasource.url=jdbc:h2:mem:demo_db
spring.datasource.url=jdbc:h2:file:./src/main/resources/data/moviebookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.enabled=false
