spring.application.name=ecommerce-app
server.port=8080
# Data Source & JPA Properties
#spring.datasource.url=jdbc:mysql://localhost:3306/yourDatabaseName
#spring.datasource.username=root
#spring.datasource.password=YourPassword
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:ecomdb
spring.datasource.driverClassName=org.h2.Driver

# auto-run schema.sql / data.sql
spring.sql.init.mode=always

# H2 console (for teaching)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console