CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  price DOUBLE NOT NULL,
  quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS customer (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS cartitem (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customerid INT NOT NULL,
  productid INT NOT NULL,
  quantity DOUBLE NOT NULL
);